# My donation options

github: TheLastGimbus - uncomment when submitted
ko_fi: thelastgimbus
liberapay: TheLastGimbus
custom: [ https://www.buymeacoffee.com/TheLastGimbus, https://www.paypal.me/TheLastGimbus ]
