# This is a basic workflow to help you get started with Actions

name: Windoza standalone .exe

# Controls when the action will run. 
on:
  # TODO: Make this run on release

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      # Runs a set of commands using the runners shell
      - name: Install pyinstaller
        run: pip install pyinstaller
      - name: Build dist/
        run: pyinstaller --onefile google_photos_takeout_helper\__main__.py
      - name: Show whats going on
        run: |
          ls
          ls build
          ls dist
        
