# Build windoza .exe with pyinstaller and add it to latest release

name: Windoza standalone .exe

on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install pyinstaller
        run: pip install pyinstaller
      - name: Build dist/
        run: pyinstaller --onefile google_photos_takeout_helper\__main__.py
      - name: Show whats going on
        run: |
          ls
          ls build
          ls dist
          type __main__.spec
      - name: Get latest tag
        id: latesttag
        uses: WyriHaximus/github-action-get-previous-tag@v1
      - name: Upload exe to latest release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: .\dist\__main__.exe
          asset_name: takeout-helper.exe
          tag: ${{ steps.latesttag.outputs.tag }}
        
